### ISSUE TITLE
*** Check failure stack trace: ***

### ISSUE THREAD

**Issue by maxfax28** [yihui-he/resnet-cifar10-caffe#10]
Hi, I tried to train, but whenever I do, I always get an error and the train.sh closes.
I have checked the logs and this is what always appears.

+ echo Logging output to resnet-110/logs/resnet-110__2017-09-20_18-39-43.log
Logging output to resnet-110/logs/resnet-110__2017-09-20_18-39-43.log
+ D:/software/caffe/scripts/build/tools/caffe train -gpu 1 -solver resnet-110/solver.prototxt -sighup_effect stop
*** Check failure stack trace: ***
+ set +x

I am unsure what I have done wrong as I am pretty sure I have followed your README completely. 
If you have any idea what could be causing the issue I would appreciate it.

**Comment by ethanhe42** [comment]
need details below 、'*** Check failure stack trace: ***'

**Comment by maxfax28** [comment]
What specific details do you need?

I directly downloaded the training & testing LMDB into the folder,
I activated the net_generator.py in Command Prompt, which printed this in the Command Prompt

> D:\resnet-cifar10-caffe>net_generator.py
> first_conv
> group0_block0_sum
> group0_block1_sum
> group0_block2_sum
> group0_block3_sum
> group0_block4_sum
> group0_block5_sum
> group0_block6_sum
> group0_block7_sum
> group0_block8_sum
> group0_block9_sum
> group0_block10_sum
> group0_block11_sum
> group0_block12_sum
> group0_block13_sum
> group0_block14_sum
> group0_block15_sum
> group0_block16_sum
> group0_block17_sum
> group1_block0_sum
> group1_block1_sum
> group1_block2_sum
> group1_block3_sum
> group1_block4_sum
> group1_block5_sum
> group1_block6_sum
> group1_block7_sum
> group1_block8_sum
> group1_block9_sum
> group1_block10_sum
> group1_block11_sum
> group1_block12_sum
> group1_block13_sum
> group1_block14_sum
> group1_block15_sum
> group1_block16_sum
> group1_block17_sum
> group2_block0_sum
> group2_block1_sum
> group2_block2_sum
> group2_block3_sum
> group2_block4_sum
> group2_block5_sum
> group2_block6_sum
> group2_block7_sum
> group2_block8_sum
> group2_block9_sum
> group2_block10_sum
> group2_block11_sum
> group2_block12_sum
> group2_block13_sum
> group2_block14_sum
> group2_block15_sum
> group2_block16_sum

Then I specified the caffe path in train.sh, 
Finally I attempted to execute the train.sh in Command Prompt like this

> D:\resnet-cifar10-caffe>train.sh 1 resnet-110

Is there something from that I either missed or did wrong?

**Comment by ethanhe42** [comment]
There should be some Trace info under `Check failure stack trace`. Try excute commands inside train.sh without logging, and show me the failure info

**Comment by maxfax28** [comment]
In the shell script this is what it shows. After Check Failure Stack Trace all it says is + set +x

> + GPUs=1
> + NET=resnet-110
> + mkdir resnet-110/logs
> + mkdir resnet-110/snapshot
> + EXTRA_ARGS=
> + EXTRA_ARGS_SLUG=
> + solver=resnet-110/solver.prototxt
> ++ date +%Y-%m-%d_%H-%M-%S
> + LOG=resnet-110/logs/resnet-110__2017-09-20_23-12-26.log
> + exec
> ++ tee -a resnet-110/logs/resnet-110__2017-09-20_23-12-26.log
> + echo Logging output to resnet-110/logs/resnet-110__2017-09-20_23-12-26.log
> Logging output to resnet-110/logs/resnet-110__2017-09-20_23-12-26.log
> + D:/software/caffe/scripts/build/tools/caffe train -gpu 1 -solver resnet-110/solver.prototxt -sighup_effect stop
> *** Check failure stack trace: ***
> + set +x

**Comment by ethanhe42** [comment]
that's weird. Haven't test my code under windows. If `D:/software/caffe/scripts/build/tools/caffe train -gpu 1 -solver resnet-110/solver.prototxt -sighup_effect stop` only output `*** Check failure stack trace: ***`, I'm not able to provide any help.
