### ISSUE TITLE
module cfgs has no no attribute 'plots'

### ISSUE THREAD

**Issue by WenyangLiu-zz** [yihui-he/resnet-cifar10-caffe#14]
Hello, when I run the plot.py, the plot.py call the module cfgs and the cfgs doesn't have any attribute 'plots'. By the way, does the PATH/TO/LOGS mean the path of the log file in resnet-20/log.

**Comment by ethanhe42** [comment]
probably I forgot to add that... 
yes

**Comment by WenyangLiu-zz** [comment]
So could you please modify the file of cfgs.py? Thanks
