### ISSUE TITLE
cannot reproduce your learning curve

### ISSUE THREAD

**Issue by wenli-vision** [yihui-he/resnet-cifar10-caffe#9]
Hi, I tried to train resnet-20 using your prototxts, but failed to reproduce your learning curve. For example, when iter_num = 10,000, my test accuracy is still around 0.8. May you please also share your training logs? Thanks a lot!

**Comment by ethanhe42** [comment]
https://github.com/yihui-he/resnet-cifar10-caffe/blob/master/resnet-20/logs/resnet-20__2016-08-14_00-25-56.log

**Comment by wenli-vision** [comment]
I see. you used 4 GPUs. So your actual batch_size is 128*4.

BTW, I have another question regarding the prototxt, should there be a ReLU layer after each Eltwise SUM layer?

**Comment by wenli-vision** [comment]
see the official ResNet50 
https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-50-deploy.prototxt
`
layer {
	bottom: "res2a_branch1"
	bottom: "res2a_branch2c"
	top: "res2a"
	name: "res2a"
	type: "Eltwise"
}

layer {
	bottom: "res2a"
	top: "res2a"
	name: "res2a_relu"
	type: "ReLU"
}
`

**Comment by ethanhe42** [comment]
(1) that's a big mistake I didn't realize!   
(2) You are right. However, the performance is better without ReLU on CIFAR-10.
